//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 风行者.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("风行者.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     var hasOwnProperty = Object.hasOwnProperty;
        ///    var iproxy =&apos;DIRECT&apos;;
        ///    var squidproxy =  &quot;PROXY ServerIP:1012;&quot;;
        ///    var list = [
        ///        [
        ///        ],
        ///        [
        ///                [16777472, 4294967040],
        ///                [16777728, 4294966784],
        ///                [16779264, 4294965248],
        ///                [16785408, 4294959104],
        ///                [16842752, 4294967040],
        ///                [16843264, 4294966784],
        ///                [16843776, 4294966272],
        ///                [16844800, 4294965248],
        ///                [1684684 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string hacker {
            get {
                return ResourceManager.GetString("hacker", resourceCulture);
            }
        }
        

        public static string myStringWebResource {
            get {
                return ResourceManager.GetString("myStringWebResource", resourceCulture);
            }
        }
        

        public static string xmlURL {
            get {
                return ResourceManager.GetString("xmlURL", resourceCulture);
            }
        }
    }
}
